### ISSUE TITLE
Allow customising underscore template settings

### ISSUE THREAD

**Issue by powmedia** [powmedia/backbone-forms#102]

**Comment by glenpike** [comment]
Think this has been fixed / added right?

**Comment by exussum12** [comment]
running `git grep "_\.templateSettings"` suggests not

**Comment by glenpike** [comment]
You can pass settings to the template function - http://underscorejs.org/#template - I think the issue I fixed in #482 should now make this feature work properly?

**Comment by exussum12** [comment]
@glenpike apologies, on an outdated master!
