### ISSUE TITLE
Best practice for file upload

### ISSUE THREAD

**Issue by moskrc** [powmedia/backbone-forms#24]
Hi!

My model has a field of type File. How can I organize a file upload through backbone-forms? Is it possible? Point me in the right direction please. I'm using django-tastypie.

Thanks,
Vitaliy

**Comment by gadikotamohan** [comment]
@powmedia @moskrc   Alternatively we add type Image to `Backbone.Form.editors` and restrict its content to image/* and read file as data-url without introducing any dependencies on other libraries and their bells and whistles. Like https://gist.github.com/gadikotamohan/c732a5148cddde3b00a08858273e8c35
