### ISSUE TITLE
Disable a field of form

### ISSUE THREAD

**Issue by Chrysweel** [powmedia/backbone-forms#325]
Hello.

In the documentation I see: 

The attribute:

> editorAttrs

And in the groups google, I read the option:

> form.schema.name.editorAttrs.disabled = true;

But it doesnt work for me:

How can I disable a field of form ? And Can I do it of way dinamically  ?

Thanks in advance !

**Comment by Niranthari** [comment]
can we even edit any of the editorAttrs 
this.form.fields.name.editor.$el.attr('data-placement', 'top');

**Comment by glenpike** [comment]
Hi, you can specify the editorAttrs in the schema - https://github.com/powmedia/backbone-forms#main-attributes and you can manipulate the DOM however you like - Backbone Forms doesn't restrict you, but bear in mind, if a form re-renders, you may lose your changes.

Your best bet for setting the attributes is to set in the schema, if this is something that appears on multiple fields, consider specifying your own template: https://github.com/powmedia/backbone-forms#customising-templates
