### ISSUE TITLE
0.13.0 and 0.14.0 releases contain wrong versions of files

### ISSUE THREAD

**Issue by coroneos** [powmedia/backbone-forms#404]
The incorrect version of the backbone-forms library is being returned from cdnjs. This appears to afflict at least 0.13.0 and 0.14.0. Here are a couple of the afflicted files:

https://cdnjs.cloudflare.com/ajax/libs/backbone-forms/0.14.0/backbone-forms.js
https://cdnjs.cloudflare.com/ajax/libs/backbone-forms/0.13.0/backbone-forms.js

I originally assumed this to be an issue on their end, but after looking into it, they said the backbone-forms releases themselves appear to be the problem. I downloaded the releases from this repository and verified that this is in fact the case. I can also verify that the library itself is outdated and not merely the banner comment's version number because there are features added in 0.14.0 (like the addition of the submitButton property) that are missing, so the release .zip definitely contains the incorrect contents. 

Here's the issue thread on the cdnjs GitHub: https://github.com/cdnjs/cdnjs/issues/3637

**Comment by drewfreyling** [comment]
Has this been fixed?

**Comment by glenpike** [comment]
Fixed with https://github.com/powmedia/backbone-forms/tree/v0.14.1 release
