### ISSUE TITLE
Geolocation/Geocoordinates Map plugin?

### ISSUE THREAD

**Issue by rjsteinert** [powmedia/backbone-forms#409]
Has anyone heard of a plugin for Backbone-Forms that allows would render a field as a map that you can select geocoordinates on?  In particular I have a need to allow folks to select areas on a map (fields on farms).

**Comment by bielfrontera** [comment]
@rjsteinert I have developed a custom editor to manage a bounding box field. It uses leafletjs with two plugins (Draw and Pan). I have taken the date field editor as a example.

Here you have a gist with the code: https://gist.github.com/bielfrontera/de36b1f510000ccbaf48

![image](https://cloud.githubusercontent.com/assets/2402407/6803956/3c1156e0-d23b-11e4-9332-c8bedcddc202.png)

**Comment by rjsteinert** [comment]
@bielfrontera Cool :). That would be cool to see as a [bower](http://bower.io/) package.

**Comment by glenpike** [comment]
Looks like question was answered.  Will close this now.
