### ISSUE TITLE
"bower install" latest listed Backbone Forms v0.14.0 but actually v0.13.0

### ISSUE THREAD

**Issue by mromanoff** [powmedia/backbone-forms#418]
after running bower install in console i get 
bower backbone-forms#~0.14.0       not-cached git://github.com/powmedia/backbone-forms.git#~0.14.0
bower backbone-forms#~0.14.0          resolve git://github.com/powmedia/backbone-forms.git#~0.14.0
bower backbone-forms#~0.14.0         download https://github.com/powmedia/backbone-forms/archive/v0.14.0.tar.gz
bower backbone-forms#~0.14.0          extract archive.tar.gz
bower backbone-forms#~0.14.0         resolved git://github.com/powmedia/backbone-forms.git#0.14.0
bower backbone-forms#~0.14.0          install backbone-forms#0.14.0

actually I get v0.13.0

**Comment by maxmx** [comment]
:+1: please fix.

**Comment by natkuu** [comment]
:+1: Please fix!

**Comment by natkuu** [comment]
This has happened because the release tag v0.14.0 was created before the version numbers were changed. 

b1d90a5c1decaeeafe523037806fc61f780c3b8a - is the release tag.
e0f2e7a9403ab183f1fa533ad6c72bf13a71e7e2 - is the versioning increment. 

bower.json was updated: fda7dc032dbce72e170c3d398129a4dadcf493b7

suggest fix: release new version number.

**Comment by GabeIsman** [comment]
This is also a problem on npm! The builds are old and contain old bugs. Please release a new version!

**Comment by mdesign83** [comment]
:+1: Please fix!

**Comment by glenpike** [comment]
Still not fixed, come on already, it's not that hard - they've told you how...

**Comment by fonji** [comment]
Even though @powmedia has public activity in the last few days, this project hasn't been touch since 7 months. I guess he's too busy.

**Comment by glenpike** [comment]
Okay, I forked & created a branch from master (which doesn't seem to show up in Github even though my command line says it's on the remote).  I've updated the patch version in the files, fixed the build scripts and done a build based on fda7dc0  I tried to do a pull request #480, but this is relative to master which is wrong.

The commit bed2295 could be merged into a branch from the above commit and then tagged - which I've done on my fork - you can't merge tags across repos.  So @powmedia can do that if he wishes, then people with ~0.14.0 will be able to update via bower.

**Comment by maxmx** [comment]
Issue is a year old and he's hardly active.
![screen shot 2015-11-13 at 11 21 55 am](https://cloud.githubusercontent.com/assets/2332621/11151425/0e218282-89fb-11e5-8a97-9b978dab8ae7.png)

All hope is lost.

@powmedia at least add an admin contributor if one is willing to take over.

**Comment by fonji** [comment]
@glenpike [I can see your repository.](https://github.com/glenpike/backbone-forms)
Can you create a pull request? I think it will have better chances to be changed that way.

@maxmx maybe he's busy but just not on github or on private projects (as I am). But I agree, we need an admin. But who would it be?
I sadly don't have time for this. Anyway, I would prefer start from scratch in coffeescript and using backbone.marionette.

**Comment by AlJohri** [comment]
reach out: charlie@powmedia.co.uk

**Comment by glenpike** [comment]
@fonji - do you know how I can create a pull request that doesn't go to master.  I think I need a branch in this repo to target?

**Comment by glenpike** [comment]
Alas, I don't really have much time to be an admin, sorry :-1:

**Comment by fonji** [comment]
@glenpike I think you should target master (it's the branch where you want your stuff to go)

**Comment by glenpike** [comment]
@fonji - not sure I want to target master as it's moved on since fda7dc0 and I was just creating a bower release version to fix the problem there rather than a "latest" release.

**Comment by fonji** [comment]
@glenpike I see. I guess we need input from @powmedia then...

**Comment by exussum12** [comment]
@philfreo  is this something you can do or is it just @powmedia ?

**Comment by jgkinnear** [comment]
Well this was a little frustrating. Never feels right using a module where the admin is MIA :(

**Comment by glenpike** [comment]
Good news, I have managed to speak to Charles and he's opened up admin access for me and is hopefully doing the same for someone else :8ball:

**Comment by fonji** [comment]
Hooray for @glenpike ! :+1:

**Comment by glenpike** [comment]
See the v0.14.1 release / tag.
