### ISSUE TITLE
Bootstrap vs Bootstrap 3 Template

### ISSUE THREAD

**Issue by reustle** [powmedia/backbone-forms#431]
https://github.com/powmedia/backbone-forms/tree/master/distribution/templates

I noticed that there is a bootstrap3 template, along with a bootstrap template. It appears the bootstrap3 template has not been updated in a year, but the other has been updated somewhat recently. What is the status of these? Are they trying to be merged together? Using the bootstrap3 template works while using bs3, and the other does not, so I don't think it is deprecated yet.

I would hate to see bug fixes being made to the bs2 template and not bs3

**Comment by nicolaskern** [comment]
The BS3 template doesn't comply with BS' right ways of doing.
We modified it, to properly handle checkboxes/radios, form-groups...
