### ISSUE TITLE
Render function in the cildren of a list runs in list scope

### ISSUE THREAD

**Issue by devel-pa** [powmedia/backbone-forms#434]
I hope it's an issue on my side, but let's describe it:
When rendering a list, the item render and the render of the object inside it the "this" keyword represents the list;

**Comment by devel-pa** [comment]
Sry, I've tried to reproduce the behavior without success outside my application. I'll research more and in case I can obtain something valid I'll give you the code. Thanks

**Comment by glenpike** [comment]
Closing as thread is old.  Please feel free to re-open if you found problem / solution.
