### ISSUE TITLE
Dynamically creating model schema?

### ISSUE THREAD

**Issue by daveed80** [powmedia/backbone-forms#435]
I have the following json structure:

{"Id":0,"Alias":"Person",
	"Traits":[
		{"TraitId":0,
		"Ignore":false,
		"AttrName":"FirstName",
		"AttrValue":null,
		"DataType":"string",
		"CoreValue":true,
		"Required":true,
		"DefaultResponse":null,
		"Sequence":0,
		"CodeType":null,
		"Linked":false,
		"TypeAlias":null,
		"SummaryDisplay":1,
		"CodeValues":[]}
		]
}

I wasn't sure if this is possible (out of the box or otherwise), but I would like to dynamically create the model schema that will be used for the form. This seems like it could be done, however the real issue is regarding setting the model. The model 'schema' that I'd like to set is actually on the nested 'Traits' array.

Again, is it possible to dynamically create the models 'schema', and bind form events to the nested array properties when calling form.commit() ?

**Comment by glenpike** [comment]
Closing as this looks like a question that's been answered rather than a bug.  Please re-open if I'm wrong.
