### ISSUE TITLE
customize a form

### ISSUE THREAD

**Issue by zhailei31665431** [powmedia/backbone-forms#441]
I have a question:

In the project, I need to customize a form, enter a url box, a Get Info button, a Close button. In the Get Info button clicks when information needs to get to the url input box, and converted into another view. Changes into the original style click the Close button. Also listening url box contents using regular expressions to ensure access to information about whether the button can be clicked.

I have not got a clue, use our components. Help

**Comment by powmedia** [comment]
I don't fully understand what you want to do but you can look into Custom Templates to customise the form (see Readme) and look at the Validation section for using regular expressions.  It sounds like a lot of the other stuff you want to do is more generic Backbone work which is outside the scope of Backbone Forms.
