### ISSUE TITLE
Property order for a dynamically generated schema

### ISSUE THREAD

**Issue by trueg** [powmedia/backbone-forms#442]
First of all: **thanks a lot for your work on Backbone-Forms**. It makes my life so much simpler.

I have only one problem at this point: I am dynamically creating the schema from an external source. This works fine except that I cannot control the order of the form fields. Is there a way to do that?

And if not, can you point me to the code where this could be added? Maybe using a separate option to list the order of properties or using a (rather ugly) weighting option on the schema entries...

**Comment by powmedia** [comment]
Sure, you can use the `fieldsets` form option for specifying the order and dividing fields into fieldsets if required. E.g.:

```
var Form = new Backbone.Form({
  schema: {
    age: 'Text',
    name: 'Text',
  },
  fieldsets: ['name', 'age']
});
```

**Comment by trueg** [comment]
Brilliant, thanks a lot. Should have seen that myself.
