### ISSUE TITLE
Sub schema's type, title, editor class , validators etc are not applied to the field.

### ISSUE THREAD

**Issue by deepa-a** [powmedia/backbone-forms#450]
I have a schema where there are nested fields for example

schema:
    spendlimits:
      type: 'Object'
      subSchema:
        name:
          type: 'Select'
          options: ['Monthly Spend', 'Name']
          title: 'Spend Limit Name'
          editorClass: 'pure-input-1-3'
          validators: [
            type: 'required'
            message: 'Cannot be empty'
          ]
        threshold:
          type: 'Text'
          title: 'Spend Limit Threshold'
          editorClass: 'pure-input-1-3'
          validators: [
            type: 'required'
            message: 'Cannot be empty'
          ]

None of the attributes like type, title etc are applied to the form field. Even the validators and Editor class. Is this an issue with subschema?

**Comment by exussum12** [comment]
Validators should do in master (not on the last release) Can you set a jsfiddle up ?

**Comment by deepa-a** [comment]
Thanks!, got the latest and seems to work.
