### ISSUE TITLE
Put HTML content after editor

### ISSUE THREAD

**Issue by amiceli** [powmedia/backbone-forms#455]
I created a custom template for my checkbox editor : 

    var checkboxFieldTemplate = _.template('\
        <div class="form-group field-<%= key %>">\
            <span data-editor>\
                <label class="checkboxLabel" for="<%= editorId %>"><%= title %></label>\
             </span>\
             <p class="help-block"><%= help %></p>\
        </div>\
    ');

When the editor is created my label is before my input. There is a way to put thelabel after my input without JavaScript DOM manipulation ?

Thanks for your help

**Comment by powmedia** [comment]
Yes, this should work:

```
var checkboxFieldTemplate = _.template('\
    <div class="form-group field-<%= key %>">\
         <span data-editor></span>\
         <label class="checkboxLabel" for="<%= editorId %>"><%= title %></label>\
         <p class="help-block"><%= help %></p>\
    </div>\
');
```

**Comment by amiceli** [comment]
It doesn't work, I would have this HTML result : 

    <span data-editor>
        <label>Label</label>
        <input type="checkbox" />
    </span>    

The label musts be in the span before the input.

Thanks
