### ISSUE TITLE
"submit" event not firing?

### ISSUE THREAD

**Issue by afflicto** [powmedia/backbone-forms#458]
I've created my form:

```javascript
form = new Backbone.Form({model: new UserModel});
```

And trying to listen for submit event:
```javascript
form.on('submit', function(e) {
    e.preventDefault();
});
```

But the event doesn't seem to be firing.
Using latest version (0.14.0), installed from Bower.

**Comment by mrnull** [comment]
I have same problem.
Provide solution, if you please.
