### ISSUE TITLE
Custom list template issue

### ISSUE THREAD

**Issue by wesvetter** [powmedia/backbone-forms#461]
I'm trying to customize the List template but not having any success customizing the list container (I can customize the list items successfully).

I've made a Jsfiddle demonstrating the issue: http://jsfiddle.net/wesvetter/vu8z0t3q/1/ 

If I add the `template` attribute to the `notes` field it seems to interfere with the form template and only renders the container (with no list items).

I was able to get it to work by modifying `List.initialize` to look at a different property on the schema (`schema.listTemplate`):

```js
    ...
    var schema = this.schema;
    if (!schema) throw new Error("Missing required option 'schema'");

    // I modified this line, and then used the listTemplate property in my schema
    this.template = options.template || schema.listTemplate || this.constructor.template;

    //Determine the editor to use
    this.Editor = (function() {
    ...
```

Am I missing something obvious or is it not possible to use a custom template in the schema definition? It seems like this may be related to issue #405.

**Comment by glenpike** [comment]
If you override template for the schema item, this changes the Field template rather than the List one.

If you want to override the template used for the list, you can do the following after you've declared list_tmpl

``` Backbone.Form.editors.List.template = list_tmpl;```

See https://jsfiddle.net/glenpike/vnxopbdq/1/

I guess we could improve the List editor type by allowing the "wrapper" template for the List items to be overridden.  We'd need to do something like:

```
this.template = options.template || schema.listTemplate || this.template || this.constructor.template;
```
in
https://github.com/powmedia/backbone-forms/blob/master/src/editors/extra/list.js#L35 to mirror the way that Field behaves and allow for listTemplate to be declared on the schema - @exussum12 do you think it's worth it?

**Comment by wesvetter** [comment]
Modifying `Backbone.Forms.editors.List.template` would modify the template for all instances of a List editor, no? Ideally you should be able to have different List's with different templates.

**Comment by glenpike** [comment]
Yes, it would modify it for all instances of forms you create that runtime, so it's not an ideal solution, but a possible workaround if you only have a single list type.

**Comment by wesvetter** [comment]
FWIW, the modification you proposed is what I've been using in my hard-fork of BBF: https://github.com/wesvetter/backbone-forms/commit/6b37616a7b669965c6d42f7e274ee3fe8f03f4ab

That seems to work fine; and `listTemplate` is a consistent name with `itemTemplate`. e.g.
```coffeescript
schema:
  foo:
    type: 'List'
   itemType: 'Object'
   itemTemplate: foo_tmpl
   listTemplate: bar_tmpl
```

**Comment by glenpike** [comment]
Do you want to add some tests and submit a pull request?

**Comment by exussum12** [comment]
@wesvetter this looks a good change, Can you make a pull request ?

**Comment by wesvetter** [comment]
Sorry, just got back from holiday, I'll submit a PR for this this week.

**Comment by glenpike** [comment]
Nice, thank you :+1:   Remember not to submit the "built" code in a PR and if you are able to write any tests for the scenario you're fixing, then that would be great!
