### ISSUE TITLE
v0.14.0 release missing number validator

### ISSUE THREAD

**Issue by cshenoy** [powmedia/backbone-forms#463]
The v0.14.0 official release is missing the `number` validator. Because of this, it's also missing in the npm repo.

https://github.com/powmedia/backbone-forms/blob/b1d90a5c1decaeeafe523037806fc61f780c3b8a/distribution/backbone-forms.js

**Comment by glenpike** [comment]
See  #418

**Comment by glenpike** [comment]
v0.14.1 released - 7aad9e3be590b0bda964f6156b7a438e89d00e45
