### ISSUE TITLE
Backbone 1.2.0 compatibility

### ISSUE THREAD

**Issue by Integral** [powmedia/backbone-forms#464]
Hello!

It seems that new version of Backbone breaks backbone-forms. At least bootstrap3.js template know nothing about Form variable.

**Comment by whitmanc** [comment]
@Integral You can fix it by replacing `Form.` with `Backbone.Form.` it seems

**Comment by glenpike** [comment]
Closing this issue as it's been answered - see the example: https://github.com/powmedia/backbone-forms/blob/master/examples/register-form-custom-template/main.js#L3
