### ISSUE TITLE
Submit event not firing

### ISSUE THREAD

**Issue by mrnull** [powmedia/backbone-forms#467]
I have following code.

    jQuery(document).ready(function($) {
        var NewOrderForm = Backbone.Form.extend({
        template: _.template($('#new-order-form-template').html()),  
        schema: {
            url: { validators: ['required'] },
        }
    });

    var newOrderForm = new NewOrderForm();
    newOrderForm.render();
    $('#new-order-form-wrapper').append(newOrderForm.el);

    newOrderForm.on('submit', function(e){
            e.preventDefault();
            console.warn(newOrderForm.commit());
        });
    });

In my template I have a button, which submits the form.
    < button class="btn btn-primary btn-labeled fa fa-shopping-cart ladda-button" id="buy-button" >< span class="ladda-label" >Buy< /span>< /button>

When button is clicked, submit event is not firing and form is submitting, but it is must not.

**Comment by fonji** [comment]
It seems like there's nothing in your code telling your form to submit.
Just adding a button doesn't exactly means it should submit the form, you may want to perform another action.
Try by replacing your button with
```html
<input type="submit" class="btn btn-primary btn-labeled fa fa-shopping-cart ladda-button" id="buy-button" >< span class="ladda-label" >Buy< /span>< /input>
```
Or something similar, as I'm not sure input[type=submit] allow inner html.

You can also listen to ```#buy-button clicks``` and call nowOrderForm.submit().

**Comment by exussum12** [comment]
Closing as the code @fonji suggests is correct
