### ISSUE TITLE
Bower.json include List and Bootstrap modal

### ISSUE THREAD

**Issue by marisbest2** [powmedia/backbone-forms#468]
It seems that when installing via Bower it only includes bootstrap-forms.js and not the List or Modal files.

**Comment by AlJohri** [comment]
I believe this is by design. Installing via bower, you can specify the bower_components you want in your index.html file. You may also be able to override the `main` attribute if you're using some `wiredep` magic.

**Comment by glenpike** [comment]
I'm guessing you wanted the bower.json to specify Bootstrap as a dependency?  I think this is probably not going to happen as it is an optional thing, but you are able to install these yourself with Bower.

Is that acceptable?
