### ISSUE TITLE
how to use type List  with NestedModel without modal window?

### ISSUE THREAD

**Issue by comalex** [powmedia/backbone-forms#470]
hi, i want use list with nested model like it ![Image](http://s3.amazonaws.com/awesome_screenshot/8409797?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1435053340&Signature=Fgnk%2FFsbP10fcTfS1rC3%2FVtgWXk%3D). How can  i do it? thank

**Comment by fonji** [comment]
There's a pull request #453 documenting it.
Here's a copy-paste of the solution:
```js
// Use standard 'Object' editor for list items.
Form.editors.List.Object = Form.editors.Object;

// Use standard 'NestedModel' editor for list items.
Form.editors.List.NestedModel = Form.editors.NestedModel;
```

**Comment by comalex** [comment]
thank, but how i can change atribute name? for example 
first:
    <input name="article-0">
    <input name="id-0">
another:
    <input name="article-1">
    <input name="id-1">
?

**Comment by fonji** [comment]
I'm not sure what you're trying to do.
You either want two lists, or one list with another editor with two fields.

**Comment by comalex** [comment]
i want do formset. To save the result on a server i need that all  input have different name. If i click button "add" generates the same name...

**Comment by fonji** [comment]
Can't you manage arrays on the server?
I mean, if you receive something like this:
```js
{
  things: [
    {
      article: 'article-1-value',
      id: 'article-1-id'
    },
    {
      article: 'article-2-value',
      id: 'article-2-id'
    },
  ]
}
```
It seems cleaner than guessing input ids.

**Comment by comalex** [comment]
yes, it sounds good, thank

**Comment by glenpike** [comment]
Closing as question appears to have been answered.
