### ISSUE TITLE
How to attach event handler in backbone forms

### ISSUE THREAD

**Issue by manu4543** [powmedia/backbone-forms#472]
I am using Backbone form - https://github.com/powmedia/backbone-forms.

In few fields I am using custom template for a specific field. Lets say something like this

![screen shot 2015-07-01 at 4 22 45 pm](https://cloud.githubusercontent.com/assets/2187409/8453124/0e6e8452-200f-11e5-8a16-f6309f0a2dda.png)

Now Lets say I want to attach a click event handler to "Add month". What is the best way to accomplish it. I see that Backbone.Form is extending Backbone.View which accepts events object. But when I pass that while doing new Backbone.Form() it does't do anything.

JsFiddle for better understanding - http://jsfiddle.net/40qysLL3/1/

**Comment by denheck** [comment]
@manu4543 It looks like you can use the same events hash you would normally pass to Backbone.View. Take a look at my updated version of your JsFiddle here: http://jsfiddle.net/40qysLL3/3/

However, you will have to extend Backbone.Form.prototype.events to avoid overwriting any Backbone form events. (https://github.com/powmedia/backbone-forms/blob/master/distribution/backbone-forms.js#L32)

**Comment by fonji** [comment]
Another option, which IMO seems better suited to your problem, is to create your own editor, which would extend one of the standard editors.
You can then listen to everything you want and have custom processing directly in the editor.

**Comment by glenpike** [comment]
Closing as no further questions have appeared.
