### ISSUE TITLE
How do I use bootstrap form wizard and form x-editable feature

### ISSUE THREAD

**Issue by cullsin** [powmedia/backbone-forms#473]
Hi,

Can you please suggest me how do I use bootstrap form wizard and x-ediable components in backbone forms ?

Thanks,
Raja K

**Comment by AlJohri** [comment]
http://stackoverflow.com/questions/31154844/backbone-js-and-dynamic-form-generation

Depending on what your definition of dynamic is, you should be able to implement this form easily using standard bootstrap-forms as was suggested in the StackOverflow question. Manipulating the schema before the form is rendered (to add or remove fields) is relatively trivial. Just change your instantiated model's schema before initializing the form. Or if the form already exists, change the schema and re-initialize. To show and hide other fields depending on the value of other fields simply listen to the change event of a particular field and toggle the "fieldClass" attribute on the others i.e. `$el.toggleClass("hidden")`.

It *might* be possible to use bootstrap form wizard but you'd probably want to re-implement it using backbone / backbone-forms. One approach could be using different fieldsets for each tab and hide and show them as you press the next button. I don't think the fieldset has a validate function but simply loop through each field within the fieldset and run their corresponding validate functions.

You can create custom editors to work with X-editable components. See the wiki page for how people have created custom editors for other plugins such as `chosen` / `select2` autocomplete, `bootstrap-datepicker`, and several more.

**Comment by glenpike** [comment]
Closing this as no further questions have appeared.
