### ISSUE TITLE
Change of ownership? Seeing loads of issue-activity all of a sudden

### ISSUE THREAD

**Issue by gebrits** [powmedia/backbone-forms#488]
I'm seeing a huge uptick on the nr of issues being posted / answered all of a sudden. Good news since I considered backbone-forms dormant for a while. 

Is there change of ownership or just renewed interest?

**Comment by fonji** [comment]
The owner of the repository just assigned collaborators, so other people can do stuff around here from now on. It seems to work pretty well!

**Comment by exussum12** [comment]
@powmedia has given access to @glenpike and myself. Just looking though all of the old issues and pull requests currently

**Comment by powmedia** [comment]
Yep, and many thanks to the new collaborators. If anyone else with
experience of the project is interested in helping as a collaborator please
let me know here.

**Comment by fonji** [comment]
I'm thinking about it, trying to estimate the time it will require.

**Comment by gebrits** [comment]
Great, cool to know. Thanks @powmedia for a great lib. Let's bring it to new heights with more eyeballs on it.
