### ISSUE TITLE
disable Date fields

### ISSUE THREAD

**Issue by SamDecrock** [powmedia/backbone-forms#497]
Hi,

How can I disable a 'Date' field? So adding disabled="disabled" to all 3 select fields?

**Comment by glenpike** [comment]
It looks like this is a bug - the hidden input in a Date editor is disabled with the disabled call, but the 3 select boxes are not.

As a workaround, you can "manually" set the disabled property on the 3 select inputs - see this [JSFiddle](https://jsfiddle.net/glenpike/yj0geg31/2/)

**Comment by SamDecrock** [comment]
All right, that works. thx!
