### ISSUE TITLE
jsfiddle demos fail

### ISSUE THREAD

**Issue by miraculixx** [powmedia/backbone-forms#500]
e.g. [user form demo](http://jsfiddle.net/gfaq5km1/)

![image](https://cloud.githubusercontent.com/assets/859611/13878255/5ea74b42-ed10-11e5-8273-7764a68b9935.png)

this happens on both firefox (45.0) and chrome (49.0.2623.87). my internet connection seems to be fine otherwise.

**Comment by glenpike** [comment]
Looks like https://rawgit.com is down

**Comment by exussum12** [comment]
Seems to be back up now ?

**Comment by glenpike** [comment]
Working now - closing this.
