### ISSUE TITLE
Taged version is not updated

### ISSUE THREAD

**Issue by thayashi** [powmedia/backbone-forms#508]
Taged version is not updated to the latest one, why it keeps as old one?

**Comment by glenpike** [comment]
Is this when you use bower install?

If so, you can workaround this by installing a specific commit if you want a more recent version - see [bower install](http://bower.io/docs/api/#install)

For example, if you want to install the most recent commit (from the other day), use this:

bower install backbone-forms#fa1628160b172038c1687bf80decb699fe80e113

You can also use:

bower install backbone-forms#master

Which will pull the latest commit, but if you save this to your bower.json config, everytime you run bower install you risk pulling a different version.

We do need to update and tag a release at some point, but need to discuss milestones with the other developers.

**Comment by thayashi** [comment]
Thank you for your comment, I got it. I'm using npm install, how do I install the latest with npm command?

**Comment by glenpike** [comment]
Hi,

You can install from a tag / commit and a repository with npm install - with caveats - you won't get the "distribution" build and to be fair, I've never tried it with require... - we need to build those and they're currently out of date - speaking to @exussum12  about this.

```
npm install git+https://github.com/powmedia/backbone-forms.git#fa16281
```

(From http://stackoverflow.com/questions/14187956/npm-install-from-git-in-a-specific-version/18049685#18049685)

Thanks for your patience.

**Comment by thayashi** [comment]
cool, thanks
