### ISSUE TITLE
Bind form to DOM element

### ISSUE THREAD

**Issue by CyCJIeHok** [powmedia/backbone-forms#509]
Hi. I have rendered DOM element I can somehow bind it to the form? Backbone.Form to monitors changes in the element.

**Comment by glenpike** [comment]
Hi,

Not as far as I am aware.  If you're using Backbone and already have a form, you probably just want to bind change events to the input(s).

So something like this:

http://stackoverflow.com/questions/10746706/attaching-backbone-js-views-to-existing-elements-vs-inserting-el-into-the-dom/10748007#10748007

Then bind events as normal:
```
var myView = Backbone.View.extend({
  events: {
    'change input': 'inputHandler'
  },

  inputHandler: function(e) {
     //handle events here: 
  },
  
  render: function() {
  //stackoverflow stuff
  }
});
```
