### ISSUE TITLE
Code mismatch between github and NPM registry

### ISSUE THREAD

**Issue by viddo** [powmedia/backbone-forms#511]
Found something odd while debugging; The latest version cached (0.14.0) on on the NPM registry doesn't match the code in the Github repo here. 

Compare https://registry.npmjs.org/backbone-forms/-/backbone-forms-0.14.0.tgz and the file `distribution/backbone-forms.js` in particular, it doesn't contain the submit events for example as declared in https://github.com/powmedia/backbone-forms/blob/r0.14.0/distribution/backbone-forms.js#L32-L36

**Comment by glenpike** [comment]
Similar to #508

**Comment by glenpike** [comment]
Published v0.14.1 tag to npm so it means bower / npmjs are in sync with the versioned releases.
