### ISSUE TITLE
lodash 4.x support

### ISSUE THREAD

**Issue by ludoo0d0a** [powmedia/backbone-forms#515]
Please add lodash 4.x support

This code won't work anymore : 

``` js
    _.each(fieldsetSchema, function(itemSchema) {
      this.fieldsets.push(this.createFieldset(itemSchema));
    }, this);
```

Because :

> Removed thisArg params from most methods because they were largely unused, complicated implementations, & can be tackled with _.bind, Function#bind, or arrow functions

https://github.com/lodash/lodash/wiki/Changelog#v400

**Comment by glenpike** [comment]
Note-to-self:
_.each() use with binding
https://github.com/powmedia/backbone-forms/blob/master/distribution/backbone-forms.js#L92
https://github.com/powmedia/backbone-forms/blob/master/distribution/backbone-forms.js#L101
https://github.com/powmedia/backbone-forms/blob/master/distribution/backbone-forms.js#L1967
https://github.com/powmedia/backbone-forms/blob/master/distribution/backbone-forms.js#L1840
