### ISSUE TITLE
Recommended way to use list.js with RequireJS

### ISSUE THREAD

**Issue by philfreo** [powmedia/backbone-forms#77]
I'm using your AMD compatible backbone-forms.amd but can you let me know the recommended way to include list.js with that?

Also it's hard to NOT use your AMD-compatible version. If I wanted to use the non-amd version using a RequireJS shim it's hard because your non-amd version checks for the existence of the "require" function :(. If you just want to detect "is this a browser" would be better to check FOR a `window` object.

**Comment by IkKan** [comment]
+1
